import React from "react";
import { Button } from "@/components/ui/button";
import { Check } from "lucide-react";
import { Link } from "react-router-dom";

export default function PricingSection() {
  const tiers = [
    {
      badge: "Entry",
      name: "Genetics Only",
      price: "$249",
      subtitle: "one-time",
      description: "Just the SelfDecode genetic test kit. Perfect for getting started with your raw DNA data.",
      features: [
        "SelfDecode Genetic Test Kit",
        "Raw Data Access",
        "Basic Genetic Reports",
        "Does NOT include Pryima Health OS AI",
      ],
      value: "Entry Level Pricing: $249",
      cta: "Buy Genetics Kit",
      highlight: false,
    },
    {
      badge: "Starter",
      name: "Core Genome",
      price: "$500",
      subtitle: "+ $9.99 / month",
      description: "Start with your DNA and the Pryima Health OS — your personal health operating system.",
      features: [
        "Pryima Health OS access",
        "SelfDecode genetics test + Pryima interpretation",
        "AI health coach that turns your genetics into daily actions",
        "Personalized dashboard with ongoing recommendations",
      ],
      value: "Founding Member Pricing: $500 (MSRP $899+)",
      cta: "Reserve Core Genome Spot",
      highlight: false,
    },
    {
      badge: "Most Popular",
      name: "Systems Deep Dive",
      price: "$1,499",
      subtitle: "one-time presale",
      description: "Deep-dive into hormones, stress, and food — mapped into your Health OS.",
      features: [
        "Everything in Core Genome",
        "Comprehensive hormone panel (sex hormones + thyroid and related markers)",
        "Cortisol / stress panel",
        "Food sensitivity testing",
        "Additional metabolic / inflammation panel (CRP, insulin, key markers)",
        "Personalized 90-day protocol generated by Pryima's AI coach",
        "Optional 1:1 'Founding Cohort Onboarding Call'",
      ],
      value: "Founding Member Pricing: $1,499 (labs + coaching MSRP $2,400+)",
      target: "For people serious about optimizing hormones, stress, and how food affects their biology.",
      cta: "Join Systems Deep Dive",
      highlight: true,
    },
    {
      badge: "Lifetime Access",
      name: "Full Omics Lifetime",
      price: "$3,499",
      subtitle: "one-time presale",
      description: "The full multi-omics stack — plus lifetime access to Pryima Health OS.",
      features: [
        "Everything in Core Genome",
        "Everything in Systems Deep Dive",
        "Gut microbiome analysis",
        "Skin microbiome analysis",
        "Founding Lifetime Access to Pryima Health OS",
        "No ongoing subscription for the core OS + AI health coach",
        "Priority access to new features and pilots",
        "Exclusive 'Founding Member' badge in the app",
      ],
      value: "Founding Member Pricing: $3,499 (full stack MSRP $5,000+ over time)",
      target: "For all-in biohackers, founders, and high performers who want the full build-out and never pay a subscription again.",
      cta: "Secure Full Omics Lifetime",
      highlight: false,
    },
  ];

  return (
    <section className="py-20 bg-gradient-to-b from-[#02040A] via-[#050814] to-[#02040A]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-12">
          <div className="inline-block mb-4">
            <div className="px-4 py-2 rounded-full bg-[#FF4A00]/20 border border-[#FF4A00]/30 backdrop-blur-sm">
              <span className="text-[#FF4A00] text-sm font-medium">Founding Member Presale</span>
            </div>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-4 text-white">
            Choose Your Pryima Founding Path
          </h2>
          <p className="text-gray-400 text-lg max-w-3xl mx-auto mb-6">
            Every tier includes genetics + the Pryima Health OS. Level up for deeper testing and, at the top level, lifetime access.
          </p>
          <div className="inline-block px-6 py-3 rounded-xl bg-[#FF4A00]/10 border border-[#FF4A00]/30">
            <p className="text-[#FF4A00] text-sm font-medium">
              Limited Founding Cohort: spots are capped for each tier to ensure white-glove onboarding.
            </p>
          </div>
        </div>

        {/* Pricing Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {tiers.map((tier, index) => (
            <div
              key={index}
              className={`relative rounded-3xl overflow-hidden transition-all duration-500 ${
                tier.highlight
                  ? "border-2 border-[#FF4A00] shadow-2xl shadow-[#FF4A00]/30 lg:-mt-4 lg:mb-4"
                  : "border border-[#FF4A00]/30 hover:border-[#FF4A00]/50"
              }`}
            >
              {/* Badge */}
              <div
                className={`px-4 py-2 text-center text-sm font-bold ${
                  tier.highlight
                    ? "bg-gradient-to-r from-[#FF4A00] to-[#FF6B00] text-white"
                    : "bg-black/80 text-[#FF4A00]"
                }`}
              >
                {tier.badge}
              </div>

              {/* Card Content */}
              <div className="p-8 bg-gradient-to-br from-black/90 to-[#050814]/90 backdrop-blur-md">
                <h3 className="text-2xl font-bold text-white mb-2">{tier.name}</h3>
                <div className="mb-4">
                  <span className="text-4xl font-bold text-[#FF4A00]">{tier.price}</span>
                  <span className="text-gray-400 text-sm ml-2">{tier.subtitle}</span>
                </div>
                <p className="text-gray-400 text-sm mb-6 leading-relaxed">{tier.description}</p>

                {/* Features */}
                <ul className="space-y-3 mb-6">
                  {tier.features.map((feature, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <Check className="w-5 h-5 text-[#FF4A00] flex-shrink-0 mt-0.5" />
                      <span className="text-gray-300 text-sm">{feature}</span>
                    </li>
                  ))}
                </ul>

                {/* Value Line */}
                <div className="mb-4 p-4 rounded-xl bg-[#FF4A00]/5 border border-[#FF4A00]/20">
                  <p className="text-[#FF4A00] text-sm font-medium">{tier.value}</p>
                </div>

                {/* Target Line */}
                {tier.target && (
                  <p className="text-gray-400 text-xs mb-6 italic">{tier.target}</p>
                )}

                {/* CTA */}
                <Link to="/signup">
                  <Button
                    className={`w-full py-6 text-lg font-semibold transition-all duration-300 ${
                      tier.highlight
                        ? "bg-gradient-to-r from-[#FF4A00] to-[#FF6B00] text-white shadow-lg shadow-[#FF4A00]/50 hover:shadow-[#FF4A00]/70"
                        : "bg-transparent border-2 border-[#FF4A00] text-[#FF4A00] hover:bg-[#FF4A00] hover:text-white"
                    }`}
                  >
                    {tier.cta}
                  </Button>
                </Link>
              </div>
            </div>
          ))}
        </div>

        {/* Fine Print */}
        <div className="text-center space-y-3 text-sm text-gray-500 max-w-4xl mx-auto">
          <p>
            You'll be contacted by our team after purchase to finalize your test kit shipments and onboarding.
          </p>
          <p>
            All testing is handled through CLIA-certified lab partners. Pryima is not a medical provider and does not replace your physician.
          </p>
          <p className="text-xs">
            Lifetime access refers to the lifetime of the Pryima Health OS product as long as it is offered in its current form. Additional third-party services or new product lines may require separate fees.
          </p>
        </div>
      </div>
    </section>
  );
}