import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Check, AlertCircle, ShoppingCart } from "lucide-react";
import { useCart } from "@/lib/CartContext";
import { toast } from "sonner";

export default function PricingSection() {
  const navigate = useNavigate()
  const { addToCart, getCartItemCount } = useCart()
  const [loadingIndex, setLoadingIndex] = useState(null)
  const [email, setEmail] = useState('')
  const [emailError, setEmailError] = useState('')

  // Validate email format
  const validateEmail = (value) => {
    if (!value) {
      setEmailError('Email is required')
      return false
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(value)) {
      setEmailError('Please enter a valid email address')
      return false
    }
    setEmailError('')
    return true
  }

  // Map tier names to server tier keys
  const TIER_KEYS = {
    GENETICS_ONLY: 'GENETICS_ONLY',
    TIER1: 'TIER1',
    TIER2: 'TIER2',
    TIER3: 'TIER3'
  }

  const tiers = [
    {
      // Package 1 — SelfDecode-only Genetics Tier (New)
      badge: "Entry",
      name: "SelfDecode-only Genetics",
      price: "$249",
      subtitle: "one-time",
      description: "Just the 1200-point SelfDecode genetic report + Pryima AI interpretation.",
      features: [
        "SelfDecode Genetic Test Kit",
        "Raw Data Access",
        "Basic Genetic Reports",
        "Does NOT include Pryima Health OS AI",
      ],
      value: "Entry Level Pricing: $249",
      cta: "Buy Genetics Kit",
      highlight: false,
      tier: TIER_KEYS.GENETICS_ONLY
    },
    {
      badge: "Starter",
      name: "Founding Tier 1",
      price: "$500",
      subtitle: "+ $9.99 / month",
      description: "Pryima Health OS + SelfDecode genetics.",
      features: [
        "Pryima Health OS access",
        "SelfDecode genetics test + Pryima interpretation",
        "AI health coach that turns your genetics into daily actions",
        "Personalized dashboard with ongoing recommendations",
      ],
      value: "Founding Member Pricing: $500 (MSRP $899+)",
      cta: "Join Tier 1",
      highlight: false,
      tier: TIER_KEYS.TIER1
    },
    {
      badge: "Most Popular",
      name: "Founding Tier 2",
      price: "$1,499",
      subtitle: "one-time presale",
      description: "Adds hormone testing, food sensitivity, cortisol/adrenal panel, etc.",
      features: [
        "Everything in Core Genome",
        "Comprehensive hormone panel (sex hormones + thyroid and related markers)",
        "Cortisol / stress panel",
        "Food sensitivity testing",
        "Additional metabolic / inflammation panel (CRP, insulin, key markers)",
        "Personalized 90-day protocol generated by Pryima's AI coach",
        "Optional 1:1 'Founding Cohort Onboarding Call'",
      ],
      value: "Founding Member Pricing: $1,499 (labs + coaching MSRP $2,400+)",
      target: "For people serious about optimizing hormones, stress, and how food affects their biology.",
      cta: "Join Tier 2",
      highlight: true,
      tier: TIER_KEYS.TIER2
    },
    {
      badge: "Lifetime Access",
      name: "Founding Tier 3",
      price: "$3,499",
      subtitle: "one-time presale",
      description: "Adds gut microbiome, facial microbiome, continuous glucose, lifetime AI coach, etc.",
      features: [
        "Everything in Core Genome",
        "Everything in Systems Deep Dive",
        "Gut microbiome analysis",
        "Skin microbiome analysis",
        "Founding Lifetime Access to Pryima Health OS",
        "No ongoing subscription for the core OS + AI health coach",
        "Priority access to new features and pilots",
        "Exclusive 'Founding Member' badge in the app",
      ],
      value: "Founding Member Pricing: $3,499 (full stack MSRP $5,000+ over time)",
      target: "For all-in biohackers, founders, and high performers who want the full build-out and never pay a subscription again.",
      cta: "Join Tier 3",
      highlight: false,
      tier: TIER_KEYS.TIER3
    },
  ];

  return (
    <section className="py-20 bg-gradient-to-b from-[#02040A] via-[#050814] to-[#02040A]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-12">
          <div className="inline-block mb-4">
            <div className="px-4 py-2 rounded-full bg-[#FF4A00]/20 border border-[#FF4A00]/30 backdrop-blur-sm">
              <span className="text-[#FF4A00] text-sm font-medium">Founding Member Presale</span>
            </div>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-4 text-white">
            Choose Your Pryima Founding Path
          </h2>
          <p className="text-gray-400 text-lg max-w-3xl mx-auto mb-6">
            Every tier includes genetics + the Pryima Health OS. Level up for deeper testing and, at the top level, lifetime access.
          </p>
          <div className="inline-block px-6 py-3 rounded-xl bg-[#FF4A00]/10 border border-[#FF4A00]/30">
            <p className="text-[#FF4A00] text-sm font-medium">
              Limited Founding Cohort: spots are capped for each tier to ensure white-glove onboarding.
            </p>
          </div>
        </div>

        {/* Email Capture */}
        <div className="max-w-2xl mx-auto mb-12 p-6 rounded-2xl bg-[#FF4A00]/10 border border-[#FF4A00]/30">
          <label className="block text-white font-semibold mb-3">
            Enter your email to get started
          </label>
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              type="email"
              placeholder="your@email.com"
              value={email}
              onChange={(e) => {
                setEmail(e.target.value)
                setEmailError('')
              }}
              onBlur={() => email && validateEmail(email)}
              className="flex-1 px-4 py-3 rounded-lg bg-black/50 border border-[#FF4A00]/30 text-white placeholder-gray-500 focus:outline-none focus:border-[#FF4A00]"
            />
            <button
              onClick={() => validateEmail(email)}
              className="px-6 py-3 rounded-lg bg-[#FF4A00] text-white font-semibold hover:bg-[#FF6B00] transition-all duration-300 whitespace-nowrap"
            >
              Verify Email
            </button>
          </div>
          {emailError && (
            <div className="flex items-center gap-2 mt-3 text-red-400 text-sm">
              <AlertCircle className="w-4 h-4" />
              {emailError}
            </div>
          )}
          {email && !emailError && (
            <p className="text-[#FF4A00] text-sm mt-3">✓ Email ready for checkout</p>
          )}
        </div>

        {/* Pricing Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          {tiers.map((tier, index) => (
            <div
              key={index}
              className={`relative rounded-3xl overflow-hidden transition-all duration-500 ${
                tier.highlight
                  ? "border-2 border-[#FF4A00] shadow-2xl shadow-[#FF4A00]/30 lg:-mt-4 lg:mb-4"
                  : "border border-[#FF4A00]/30 hover:border-[#FF4A00]/50"
              }`}
            >
              {/* Badge */}
              <div
                className={`px-4 py-2 text-center text-sm font-bold ${
                  tier.highlight
                    ? "bg-gradient-to-r from-[#FF4A00] to-[#FF6B00] text-white"
                    : "bg-black/80 text-[#FF4A00]"
                }`}
              >
                {tier.badge}
              </div>

              {/* Card Content */}
              <div className="p-8 bg-gradient-to-br from-black/90 to-[#050814]/90 backdrop-blur-md">
                <h3 className="text-2xl font-bold text-white mb-2">{tier.name}</h3>
                <div className="mb-4">
                  <span className="text-4xl font-bold text-[#FF4A00]">{tier.price}</span>
                  <span className="text-gray-400 text-sm ml-2">{tier.subtitle}</span>
                </div>
                <p className="text-gray-400 text-sm mb-6 leading-relaxed">{tier.description}</p>

                {/* Features */}
                <ul className="space-y-3 mb-6">
                  {tier.features.map((feature, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <Check className="w-5 h-5 text-[#FF4A00] flex-shrink-0 mt-0.5" />
                      <span className="text-gray-300 text-base">{feature}</span>
                    </li>
                  ))}
                </ul>

                {/* Value Line */}
                <div className="mb-4 p-4 rounded-xl bg-[#FF4A00]/5 border border-[#FF4A00]/20">
                  <p className="text-[#FF4A00] text-sm font-medium">{tier.value}</p>
                </div>

                {/* Target Line */}
                {tier.target && (
                  <p className="text-gray-400 text-xs mb-6 italic">{tier.target}</p>
                )}

                {/* CTA Button */}
                <Button
                  onClick={() => {
                    if (!tier.tier) {
                      console.error('Missing tier configuration')
                      toast.error('Package configuration error. Please refresh and try again.')
                      return
                    }

                    try {
                      setLoadingIndex(index)
                      const success = addToCart(tier.tier)
                      if (success) {
                        toast.success(`${tier.name} added to cart!`)
                        // Optional: Navigate to cart after adding
                        // navigate('/cart')
                      } else {
                        toast.error('Failed to add item to cart')
                      }
                    } catch (err) {
                      console.error('Add to cart error:', err.message)
                      toast.error('Unable to add item to cart. Please try again.')
                    } finally {
                      setLoadingIndex(null)
                    }
                  }}
                  disabled={loadingIndex !== null}
                  className={`w-full py-6 text-lg font-semibold transition-all duration-300 flex items-center justify-center gap-2 ${
                    tier.highlight
                      ? "bg-gradient-to-r from-[#FF4A00] to-[#FF6B00] text-white shadow-lg shadow-[#FF4A00]/50 hover:shadow-[#FF4A00]/70 disabled:opacity-50"
                      : "bg-transparent border-2 border-[#FF4A00] text-[#FF4A00] hover:bg-[#FF4A00] hover:text-white disabled:opacity-50"
                  }`}
                >
                  {loadingIndex === index ? (
                    '🔄 Adding...'
                  ) : (
                    <>
                      <ShoppingCart className="w-5 h-5" />
                      {tier.cta}
                    </>
                  )}
                </Button>
              </div>
            </div>
          ))}
        </div>

        {/* Fine Print */}
        <div className="text-center space-y-3 text-sm text-gray-500 max-w-4xl mx-auto">
          <p>
            You'll be contacted by our team after purchase to finalize your test kit shipments and onboarding.
          </p>
          <p>
            All testing is handled through CLIA-certified lab partners. Pryima is not a medical provider and does not replace your physician.
          </p>
          <p className="text-xs">
            Lifetime access refers to the lifetime of the Pryima Health OS product as long as it is offered in its current form. Additional third-party services or new product lines may require separate fees.
          </p>
        </div>
      </div>
    </section>
  );
}